### ISSUE TITLE
create login component

### ISSUE THREAD

**Issue by sannithibalaji** [coderplex/openrank-backend#11]

**Comment by saipavan1994** [comment]
Is this issue related to vue.js??

**Comment by pbteja1998** [comment]
N/A

**Comment by pbteja1998** [comment]
@saipavan1994 

This project is picked up again. This is under active development now. Please visit this repo from time to time to get updates about the status of the project.

Please join our [discord](https://discord.gg/QSJSbgt) server if you are interested in contributing to the project.
