### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by vasuse7en** [coderplex/openrank-backend#16]
https://github.com/blog/1184-contributing-guidelines

**Comment by vasuse7en** [comment]
hi @jbuddha @duttakapil @sannithibalaji @vinaypuppal  I understand that you guys are busy these days. can we people have a restart meeting again.:smile:

**Comment by jbuddha** [comment]
I’m fine for a restart meeting.

**Comment by pbteja1998** [comment]
@vasuse7en 

This project is picked up again. This is under active development now. Please join our [discord](https://discord.gg/QSJSbgt) server if you are interested in contributing to the project.
