### ISSUE TITLE
Python program which take Languge,codefile,testcases as input and returns whether the code passes or not

### ISSUE THREAD

**Issue by sannithibalaji** [coderplex/openrank-backend#3]

**Comment by srikanth104** [comment]
from click._compat import raw_input
import py_compile

fname = raw_input('Please enter filename...')
if (fname.__contains__(".py")):
    try:
        py_compile.compile(fname)
    except Exception as e:
        print(str(e))
else:
    fileObject = open(fname, 'r')
    print(fileObject.read())

**Comment by Yogeshwar235** [comment]
Is anyone working on this?

**Comment by jbuddha** [comment]
https://github.com/coderplex/OpenRank/pull/24

**Comment by pbteja1998** [comment]
N/A for now.
