### ISSUE TITLE
Webpage stuck at Hello from API Server

### ISSUE THREAD

**Issue by enggjiten** [coderplex/openrank-backend#34]
Hi,

I followed the steps and run both python server and node.
On webpage with port 8081, it is stuck on same page. I can't find any navigation.

![image](https://user-images.githubusercontent.com/7983176/45747015-48238f00-bc22-11e8-8b34-fde0e3b42f1f.png)

How to proceed further

**Comment by jasonlamkk** [comment]
same here, any updates

**Comment by mds-nishant** [comment]
Same here, any updates?

**Comment by duttakapil** [comment]
Hello folks, unfortunately this project is not functional. It hasn't been updated in a long time. We are looking for people who can help in rebooting this project, and perhaps even someone who can lead the development. This is a open request

**Comment by pbteja1998** [comment]
@enggjiten @jasonlamkk @mds-nishant 

This project is picked up again. This is under active development now. Please visit this repo from time to time to get updates about the status of the project.

Please join our [discord](https://discord.gg/QSJSbgt) server if you are interested in contributing to the project.
