### ISSUE TITLE
Can someone publish a OpenRank docker image to Docker Hub?

### ISSUE THREAD

**Issue by djangofan** [coderplex/openrank-backend#35]
Just a thought.  Can someone publish a OpenRank docker image to Docker Hub?   Seems like it would be a good way to advertise your claim that its easy to setup.  It would allow people to instantly try it out.

I was thinking of doing it myself but you probably would rather have your own and not have some random person like me create it right?

**Comment by infogeek** [comment]
Great suggestion. It's better to have an official docker build but until then I think it won't be a problem if you push your own build with an unofficial tag, I used a lot of docker images by other people (not in production) and doesn't really have any problem with the idea.
