### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by obedmr** [coderplex/openrank-backend#36]

**Comment by duttakapil** [comment]
Hi @obedmr, unfortunately no, this project is not active at the moment. But we are trying to put together a team to reboot the project very soon :)

**Comment by SaurabhHarwande** [comment]
Can I help? I am interested in this project.

**Comment by john-burns-arundo** [comment]
How can we build?  tests run but trying to run the api server it dies on sqlite3

**Comment by sudarshanbadireddi** [comment]
i would like to work on this project and contribute. is the team still active?

**Comment by pbteja1998** [comment]
@sudarshanbadireddi No, this project is not under active development. However, if you are interested, I was working on the same project a while before, but in PHP/Laravel and Vuejs. I had to stop working on this as I could not find the time. If you are interested in this, you can head over to [pbteja1998/OpenRank](https://github.com/pbteja1998/OpenRank) and contribute there.

**Comment by pbteja1998** [comment]
@obedmr @john-burns-arundo

This project is picked up again. This is under active development now. Please visit this repo from time to time to get updates about the status of the project.

@SaurabhHarwande @sudarshanbadireddi 

Please join our [discord](https://discord.gg/QSJSbgt) server if you are interested in contributing to the project.

**Comment by sudarshanbadireddi** [comment]
Nice thank you for letting me know
