### ISSUE TITLE
Add all contributors bot for this repository

### ISSUE THREAD

**Issue by krushiraj** [coderplex/openrank-backend#50]
Add all contributors bot to the backend repo as well. We already have it for front-end.

**Comment by krushiraj** [comment]
@vinaypuppal can you do that?

**Comment by vinaypuppal** [comment]
There is nothing to configure as coderplex org has support for it. Juts follow what I did here to add it to this repo https://github.com/coderplex/openrank-frontend/issues/12

**Comment by krushiraj** [comment]
Okay.

**Comment by krushiraj** [comment]
@all-contributors please add @pbteja1998 for code, docs
